[tool.coverage.run]
branch = true
command_line = "-m unittest"
data_file = "coverage/data.sqlite3"
omit = [
	"tests/*"
]

[tool.coverage.report]
exclude_also = [
	"def __repr__",
	"raise AssertionError",
    "raise NotImplementedError",
]

[tool.coverage.html]
directory = "coverage"

[tool.pylint.MAIN]
persistent = "no"
score = "no"